// <auto-generated />
using System;
using ElectionForecaster.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectionForecaster.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ForecastDbContext))]
    [Migration("20260704150200_AddForecastMargins")]
    partial class AddForecastMargins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ElectionForecaster.Infrastructure.Data.Entities.ApprovalRatingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ApprovePercent")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("DisapprovePercent")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("ApprovalRatings");
                });

            modelBuilder.Entity("ElectionForecaster.Infrastructure.Data.Entities.ChamberHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chamber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("DemControlProbability")
                        .HasColumnType("REAL");

                    b.Property<int>("DemSeatsHigh")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DemSeatsLow")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ExpectedDemSeats")
                        .HasColumnType("REAL");

                    b.Property<double>("ExpectedRepSeats")
                        .HasColumnType("REAL");

                    b.Property<double>("RepControlProbability")
                        .HasColumnType("REAL");

                    b.Property<int>("SimulationIterations")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Chamber");

                    b.HasIndex("Chamber", "Date")
                        .IsUnique();

                    b.ToTable("ChamberHistory");
                });

            modelBuilder.Entity("ElectionForecaster.Infrastructure.Data.Entities.ForecastHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ApprovalAdjustment")
                        .HasColumnType("REAL");

                    b.Property<double>("ApprovalWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("DemVoteShare")
                        .HasColumnType("REAL");

                    b.Property<double>("DemWinProbability")
                        .HasColumnType("REAL");

                    b.Property<double>("ExpectedDemMargin")
                        .HasColumnType("REAL");

                    b.Property<double?>("FundamentalsPrediction")
                        .HasColumnType("REAL");

                    b.Property<double>("FundamentalsWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("MarginStdDev")
                        .HasColumnType("REAL");

                    b.Property<double?>("MarketOdds")
                        .HasColumnType("REAL");

                    b.Property<double>("MarketWeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("PollingAverage")
                        .HasColumnType("REAL");

                    b.Property<double>("PollingWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("RepVoteShare")
                        .HasColumnType("REAL");

                    b.Property<double>("RepWinProbability")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("RaceId");

                    b.HasIndex("RaceId", "Date")
                        .IsUnique();

                    b.ToTable("ForecastHistory");
                });

            modelBuilder.Entity("ElectionForecaster.Infrastructure.Data.Entities.GenericBallotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("DemPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("RepPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("GenericBallot");
                });

            modelBuilder.Entity("ElectionForecaster.Infrastructure.Data.Entities.MarketOddsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DemOdds")
                        .HasColumnType("REAL");

                    b.Property<string>("ExternalMarketId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("RepOdds")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("RaceId", "Source", "Timestamp");

                    b.ToTable("MarketOdds");
                });

            modelBuilder.Entity("ElectionForecaster.Infrastructure.Data.Entities.PollEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("DemPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("Methodology")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pollster")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PollsterRating")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Population")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("RepPercent")
                        .HasColumnType("REAL");

                    b.Property<int?>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("RaceId");

                    b.HasIndex("RaceId", "Date");

                    b.ToTable("Polls");
                });
#pragma warning restore 612, 618
        }
    }
}
