using System.Net.Http.Json;
using System.Text.Json;
using ElectionForecaster.Infrastructure.Data;
using ElectionForecaster.Infrastructure.Data.Entities;
using ElectionForecaster.Infrastructure.DataSources.Interfaces;
using ElectionForecaster.Infrastructure.DataSources.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace ElectionForecaster.Infrastructure.DataSources.PredictionMarkets;

/// <summary>
/// Client for fetching prediction market data from Polymarket using direct market IDs.
/// Market IDs can be found by visiting polymarket.com/event/{slug} and checking the network tab.
/// </summary>
public class PolymarketClient : IPredictionMarketSource
{
    private readonly HttpClient _httpClient;
    private readonly ForecastDbContext _dbContext;
    private readonly ILogger<PolymarketClient> _logger;
    private readonly Dictionary<string, MarketOdds> _cachedOdds = new();
    private DateTime _lastRefresh = DateTime.MinValue;

    // Markets discovered from the Gamma API by slug (races the static map predates), and races
    // that had no market at last look — retried daily rather than on every request.
    private static readonly Dictionary<string, string> _discoveredMarketIds = new();
    private static readonly Dictionary<string, DateTime> _discoveryMisses = new();
    private static readonly object _discoveryLock = new();
    private static readonly TimeSpan DiscoveryRetry = TimeSpan.FromHours(20);

    // Polymarket API endpoint for fetching market data by ID
    private const string MarketsApiBaseUrl = "https://gamma-api.polymarket.com/markets";
    // CLOB API endpoint for historical price data
    private const string ClobApiBaseUrl = "https://clob.polymarket.com";

    // Race ID -> Polymarket market ID (the "Will the Democrats win …" party market for each 2026
    // race, where the "Yes" price is the Democratic win probability). Generated by the
    // ElectionForecaster.MarketDiscovery tool against the Gamma API — re-run it to refresh:
    // `dotnet run --project ElectionForecaster.MarketDiscovery`. The Alaska (top-four ranked-choice)
    // and California-governor (top-two) races have no such party market — only per-candidate markets
    // — so they are intentionally omitted and fall back to fundamentals+polling. Only map a race
    // here if its market question is "Will the Democrats win …"; per-candidate markets are wrong.
    private static readonly Dictionary<string, string> RaceIdToMarketId = new()
    {
        // Senate 2026
        { "AL-SEN-2026", "630627" },
        { "AR-SEN-2026", "630653" },
        { "CO-SEN-2026", "630666" },
        { "DE-SEN-2026", "630679" },
        { "GA-SEN-2026", "630692" },
        { "ID-SEN-2026", "630705" },
        { "IL-SEN-2026", "630720" },
        { "IA-SEN-2026", "630733" },
        { "KS-SEN-2026", "630746" },
        { "KY-SEN-2026", "630759" },
        { "LA-SEN-2026", "634878" },
        { "ME-SEN-2026", "630772" },
        { "MA-SEN-2026", "630790" },
        { "MI-SEN-2026", "630805" },
        { "MN-SEN-2026", "630818" },
        { "MS-SEN-2026", "631017" },
        { "MT-SEN-2026", "630831" },
        // NE maps to the "Will the Republicans win" market (634892), not the "Democrat" one: the
        // viable challenger is independent Dan Osborn, so 1 − P(Republican) is the challenger's win
        // probability (the Democrat market prices only the token Democrat at ~2%). See IndependentChallengers.
        { "NE-SEN-2026", "634892" },
        { "NH-SEN-2026", "630844" },
        { "NJ-SEN-2026", "630857" },
        { "NM-SEN-2026", "630870" },
        { "NC-SEN-2026", "630883" },
        { "OK-SEN-2026", "631030" },
        { "OR-SEN-2026", "630898" },
        { "RI-SEN-2026", "630911" },
        { "SC-SEN-2026", "630924" },
        { "SD-SEN-2026", "630937" },
        { "TN-SEN-2026", "630950" },
        { "TX-SEN-2026", "630963" },
        { "VA-SEN-2026", "630976" },
        { "WV-SEN-2026", "630989" },
        { "WY-SEN-2026", "631002" },
        // 2026 Senate special elections (appointed R incumbents): the "Will the Democrats win …"
        // party-level markets, same shape as the regular Senate mappings above.
        { "FL-SEN-2026", "631044" },
        { "OH-SEN-2026", "631057" },
        // AK-SEN is a top-four ranked-choice race with no "which party wins" market on Polymarket,
        // only per-candidate markets — intentionally unmapped so it falls back to fundamentals+polling.

        // Governor 2026
        { "AL-GOV-2026", "629270" },
        { "AZ-GOV-2026", "629183" },
        { "AR-GOV-2026", "629283" },
        { "CO-GOV-2026", "629296" },
        { "CT-GOV-2026", "629311" },
        { "FL-GOV-2026", "629324" },
        { "GA-GOV-2026", "629337" },
        { "HI-GOV-2026", "629350" },
        { "ID-GOV-2026", "629363" },
        { "IL-GOV-2026", "629376" },
        { "IA-GOV-2026", "629397" },
        { "KS-GOV-2026", "629412" },
        { "ME-GOV-2026", "629425" },
        { "MD-GOV-2026", "629438" },
        { "MA-GOV-2026", "629451" },
        { "MI-GOV-2026", "629464" },
        { "MN-GOV-2026", "629477" },
        { "NE-GOV-2026", "629490" },
        { "NV-GOV-2026", "629505" },
        { "NH-GOV-2026", "629518" },
        { "NM-GOV-2026", "629531" },
        { "NY-GOV-2026", "629544" },
        { "OH-GOV-2026", "629557" },
        { "OK-GOV-2026", "629570" },
        { "OR-GOV-2026", "629583" },
        { "PA-GOV-2026", "629614" },
        { "RI-GOV-2026", "629627" },
        { "SC-GOV-2026", "629640" },
        { "SD-GOV-2026", "629653" },
        { "TN-GOV-2026", "629666" },
        { "TX-GOV-2026", "629690" },
        { "VT-GOV-2026", "629707" },
        { "WI-GOV-2026", "629720" },
        { "WY-GOV-2026", "629733" },
        // AK-GOV (top-four ranked-choice) and CA-GOV (top-two, can be D-vs-D) have no "which party
        // wins" market on Polymarket — only per-candidate markets, which the old IDs pointed at (a
        // single Republican in AK, a single Democrat in CA showing ~0%). Intentionally unmapped so
        // both fall back to fundamentals+polling instead of a misparsed single-candidate price.
    };

    public string SourceName => "Polymarket";

    public PolymarketClient(
        HttpClient httpClient,
        ForecastDbContext dbContext,
        ILogger<PolymarketClient> logger)
    {
        _httpClient = httpClient;
        _dbContext = dbContext;
        _logger = logger;
        _httpClient.DefaultRequestHeaders.Add("Accept", "application/json");
    }

    public async Task<MarketOdds?> GetRaceOddsAsync(string raceId, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug("PolymarketClient.GetRaceOddsAsync called for {RaceId}", raceId);

        // Static mapping first, then previously discovered markets, then live slug discovery —
        // so markets Polymarket lists after this code shipped are picked up automatically.
        string? marketId;
        bool haveId;
        lock (_discoveryLock)
        {
            haveId = RaceIdToMarketId.TryGetValue(raceId, out marketId) ||
                     _discoveredMarketIds.TryGetValue(raceId, out marketId);
        }
        if (!haveId)
        {
            marketId = await DiscoverMarketIdAsync(raceId, cancellationToken);
            if (marketId is null)
            {
                _logger.LogDebug("No Polymarket market for {RaceId}", raceId);
                return null;
            }
        }

        // First check cache
        if (_cachedOdds.TryGetValue(raceId, out var cached) &&
            (DateTime.UtcNow - cached.Timestamp).TotalMinutes < 1440)
        {
            _logger.LogDebug("Returning cached odds for {RaceId}", raceId);
            return cached;
        }

        // Check database for recent data
        var recentOdds = await _dbContext.MarketOdds
            .Where(m => m.RaceId == raceId && m.Source == SourceName)
            .OrderByDescending(m => m.Timestamp)
            .FirstOrDefaultAsync(cancellationToken);

        if (recentOdds != null && (DateTime.UtcNow - recentOdds.Timestamp).TotalMinutes < 1440)
        {
            _logger.LogDebug("Returning database odds for {RaceId}", raceId);
            var odds = EntityToModel(recentOdds);
            _cachedOdds[raceId] = odds;
            return odds;
        }

        // Fetch fresh data from Polymarket
        _logger.LogInformation("Fetching fresh odds from Polymarket for {RaceId} (market ID: {MarketId})", raceId, marketId);
        var freshOdds = await FetchMarketOddsByIdAsync(raceId, marketId, cancellationToken);

        if (freshOdds != null)
        {
            _logger.LogInformation("Got fresh odds for {RaceId}: Dem={Dem:P1}, Rep={Rep:P1}",
                raceId, freshOdds.DemOdds, freshOdds.RepOdds);
            _cachedOdds[raceId] = freshOdds;
            await SaveOddsToDbAsync(freshOdds, cancellationToken);
            return freshOdds;
        }

        _logger.LogWarning("Could not get odds for {RaceId} from market {MarketId}", raceId, marketId);

        // Return cached or database data even if stale
        if (recentOdds != null)
        {
            return EntityToModel(recentOdds);
        }

        return null;
    }

    public async Task<Dictionary<string, MarketOdds>> GetAllRaceOddsAsync(CancellationToken cancellationToken = default)
    {
        // Return cached data if fresh
        if ((DateTime.UtcNow - _lastRefresh).TotalMinutes < 1440 && _cachedOdds.Count > 0)
        {
            return new Dictionary<string, MarketOdds>(_cachedOdds);
        }

        await RefreshAsync(cancellationToken);
        return new Dictionary<string, MarketOdds>(_cachedOdds);
    }

    public async Task RefreshAsync(CancellationToken cancellationToken = default)
    {
        // Static + discovered mappings both refresh; a new discovery happens lazily on first access.
        Dictionary<string, string> allMappings;
        lock (_discoveryLock)
        {
            allMappings = new Dictionary<string, string>(RaceIdToMarketId);
            foreach (var (raceId, id) in _discoveredMarketIds) allMappings.TryAdd(raceId, id);
        }
        _logger.LogInformation("Refreshing Polymarket data for {Count} configured markets...", allMappings.Count);

        var successCount = 0;
        foreach (var (raceId, marketId) in allMappings)
        {
            try
            {
                var odds = await FetchMarketOddsByIdAsync(raceId, marketId, cancellationToken);
                if (odds != null)
                {
                    _cachedOdds[raceId] = odds;
                    await SaveOddsToDbAsync(odds, cancellationToken);
                    successCount++;
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Error fetching market {MarketId} for {RaceId}", marketId, raceId);
            }
        }

        _lastRefresh = DateTime.UtcNow;
        _logger.LogInformation("Polymarket refresh complete. {Success}/{Total} markets updated.",
            successCount, allMappings.Count);
    }

    /// <summary>
    /// Finds a race's "Will the Democrats win …" market by its predictable slug
    /// (e.g. will-the-democrats-win-the-georgia-governor-race-in-2026), so markets Polymarket
    /// adds over the campaign enter the blend without a code change. Misses are retried daily.
    /// </summary>
    private async Task<string?> DiscoverMarketIdAsync(string raceId, CancellationToken cancellationToken)
    {
        lock (_discoveryLock)
        {
            if (_discoveryMisses.TryGetValue(raceId, out var lastMiss) &&
                DateTime.UtcNow - lastMiss < DiscoveryRetry)
                return null;
        }

        foreach (var slug in CandidateSlugs(raceId))
        {
            try
            {
                var json = await _httpClient.GetStringAsync($"{MarketsApiBaseUrl}?slug={slug}", cancellationToken);
                using var doc = JsonDocument.Parse(json);
                if (doc.RootElement.ValueKind != JsonValueKind.Array) continue;
                foreach (var m in doc.RootElement.EnumerateArray())
                {
                    var closed = m.TryGetProperty("closed", out var c) && c.ValueKind == JsonValueKind.True;
                    if (closed || !m.TryGetProperty("id", out var idProp)) continue;
                    var id = idProp.GetString();
                    if (string.IsNullOrEmpty(id)) continue;
                    lock (_discoveryLock)
                    {
                        _discoveredMarketIds[raceId] = id;
                        _discoveryMisses.Remove(raceId);
                    }
                    _logger.LogInformation("Discovered Polymarket market {MarketId} for {RaceId} (slug {Slug})", id, raceId, slug);
                    return id;
                }
            }
            catch (Exception ex)
            {
                _logger.LogDebug(ex, "Market discovery probe failed for {RaceId} ({Slug})", raceId, slug);
            }
        }

        lock (_discoveryLock) _discoveryMisses[raceId] = DateTime.UtcNow;
        return null;
    }

    /// <summary>Likely slugs for a race's party market, most specific first.</summary>
    private static IEnumerable<string> CandidateSlugs(string raceId)
    {
        var parts = raceId.Split('-');
        if (parts.Length < 3 || !SlugStateNames.TryGetValue(parts[0], out var state)) yield break;

        if (parts[1] == "SEN")
        {
            yield return $"will-the-democrats-win-the-{state}-senate-race-in-2026";
        }
        else if (parts[1] == "GOV")
        {
            yield return $"will-the-democrats-win-the-{state}-governor-race-in-2026";
            yield return $"will-the-democrats-win-the-{state}-governors-race-in-2026";
        }
        else if (int.TryParse(parts[1], out var district))
        {
            // House party markets are rare; probe the plausible slug forms.
            var ord = $"{district}{(district % 100 is >= 11 and <= 13 ? "th" : (district % 10) switch { 1 => "st", 2 => "nd", 3 => "rd", _ => "th" })}";
            yield return $"will-the-democrats-win-{state}s-{ord}-congressional-district-in-2026";
            yield return $"will-the-democrats-win-the-{state}-{ord}-congressional-district-race-in-2026";
        }
    }

    private static readonly Dictionary<string, string> SlugStateNames = new(StringComparer.OrdinalIgnoreCase)
    {
        { "AL", "alabama" }, { "AK", "alaska" }, { "AZ", "arizona" }, { "AR", "arkansas" },
        { "CA", "california" }, { "CO", "colorado" }, { "CT", "connecticut" }, { "DE", "delaware" },
        { "FL", "florida" }, { "GA", "georgia" }, { "HI", "hawaii" }, { "ID", "idaho" },
        { "IL", "illinois" }, { "IN", "indiana" }, { "IA", "iowa" }, { "KS", "kansas" },
        { "KY", "kentucky" }, { "LA", "louisiana" }, { "ME", "maine" }, { "MD", "maryland" },
        { "MA", "massachusetts" }, { "MI", "michigan" }, { "MN", "minnesota" }, { "MS", "mississippi" },
        { "MO", "missouri" }, { "MT", "montana" }, { "NE", "nebraska" }, { "NV", "nevada" },
        { "NH", "new-hampshire" }, { "NJ", "new-jersey" }, { "NM", "new-mexico" }, { "NY", "new-york" },
        { "NC", "north-carolina" }, { "ND", "north-dakota" }, { "OH", "ohio" }, { "OK", "oklahoma" },
        { "OR", "oregon" }, { "PA", "pennsylvania" }, { "RI", "rhode-island" }, { "SC", "south-carolina" },
        { "SD", "south-dakota" }, { "TN", "tennessee" }, { "TX", "texas" }, { "UT", "utah" },
        { "VT", "vermont" }, { "VA", "virginia" }, { "WA", "washington" }, { "WV", "west-virginia" },
        { "WI", "wisconsin" }, { "WY", "wyoming" }
    };

    private async Task<MarketOdds?> FetchMarketOddsByIdAsync(string raceId, string marketId, CancellationToken cancellationToken)
    {
        try
        {
            var url = $"{MarketsApiBaseUrl}/{marketId}";
            _logger.LogDebug("Fetching Polymarket data from {Url}", url);

            var response = await _httpClient.GetAsync(url, cancellationToken);

            if (!response.IsSuccessStatusCode)
            {
                _logger.LogWarning("Polymarket API returned {Status} for market {MarketId}",
                    response.StatusCode, marketId);
                return null;
            }

            var content = await response.Content.ReadAsStringAsync(cancellationToken);
            var market = JsonSerializer.Deserialize<PolymarketMarketResponse>(
                content,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            if (market == null)
            {
                _logger.LogWarning("Failed to parse Polymarket response for market {MarketId}", marketId);
                return null;
            }

            return ParseMarketResponse(market, raceId, marketId);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error fetching market {MarketId} for {RaceId}", marketId, raceId);
            return null;
        }
    }

    private MarketOdds? ParseMarketResponse(PolymarketMarketResponse market, string raceId, string marketId)
    {
        // The market response contains outcomePrices as a JSON array string like "[\"0.45\", \"0.55\"]"
        // and outcomes like "[\"Democrat\", \"Republican\"]" or "[\"Yes\", \"No\"]"

        var outcomes = market.GetOutcomes();
        var prices = market.GetOutcomePrices();

        if (outcomes.Count < 2 || prices.Count < 2)
        {
            _logger.LogWarning("Market {MarketId} has insufficient outcomes/prices", marketId);
            return null;
        }

        double demOdds = 0;
        double repOdds = 0;

        // Try to match outcomes to parties
        for (int i = 0; i < Math.Min(outcomes.Count, prices.Count); i++)
        {
            var outcome = outcomes[i].ToLowerInvariant();
            if (double.TryParse(prices[i], out var price))
            {
                if (outcome.Contains("democrat") || outcome.Contains("dem") || outcome == "yes")
                {
                    // For "Yes/No" markets, check the question to determine party
                    if (outcome == "yes" && market.Question != null)
                    {
                        if (market.Question.ToLowerInvariant().Contains("democrat"))
                            demOdds = price;
                        else if (market.Question.ToLowerInvariant().Contains("republican"))
                            repOdds = price;
                        else
                            demOdds = price; // Default assumption
                    }
                    else
                    {
                        demOdds = price;
                    }
                }
                else if (outcome.Contains("republican") || outcome.Contains("rep") || outcome.Contains("gop"))
                {
                    repOdds = price;
                }
            }
        }

        // If we only found one party and it's a two-outcome market, calculate the other
        if (demOdds > 0 && repOdds == 0 && outcomes.Count == 2)
        {
            repOdds = 1.0 - demOdds;
        }
        else if (repOdds > 0 && demOdds == 0 && outcomes.Count == 2)
        {
            demOdds = 1.0 - repOdds;
        }

        if (demOdds == 0 && repOdds == 0)
        {
            _logger.LogWarning("Could not parse party odds from market {MarketId}. Outcomes: {Outcomes}",
                marketId, string.Join(", ", outcomes));
            return null;
        }

        // Normalize odds to sum to 1
        var total = demOdds + repOdds;
        if (total > 0 && Math.Abs(total - 1.0) > 0.01)
        {
            demOdds /= total;
            repOdds /= total;
        }

        // Parse volume
        double? volume = null;
        if (double.TryParse(market.Volume, out var vol))
        {
            volume = vol;
        }

        _logger.LogInformation("Parsed Polymarket {RaceId}: Dem={DemOdds:P1}, Rep={RepOdds:P1}, Volume=${Volume:N0}",
            raceId, demOdds, repOdds, volume ?? 0);

        return new MarketOdds
        {
            RaceId = raceId,
            Source = SourceName,
            DemOdds = demOdds,
            RepOdds = repOdds,
            Timestamp = DateTime.UtcNow,
            Volume = volume,
            ExternalMarketId = marketId
        };
    }

    private async Task SaveOddsToDbAsync(MarketOdds odds, CancellationToken cancellationToken)
    {
        var entity = new MarketOddsEntity
        {
            RaceId = odds.RaceId,
            Source = odds.Source,
            Timestamp = odds.Timestamp,
            DemOdds = odds.DemOdds,
            RepOdds = odds.RepOdds,
            Volume = odds.Volume,
            ExternalMarketId = odds.ExternalMarketId
        };

        _dbContext.MarketOdds.Add(entity);
        await _dbContext.SaveChangesAsync(cancellationToken);
    }

    private static MarketOdds EntityToModel(MarketOddsEntity entity)
    {
        return new MarketOdds
        {
            RaceId = entity.RaceId,
            Source = entity.Source,
            DemOdds = entity.DemOdds,
            RepOdds = entity.RepOdds,
            Timestamp = entity.Timestamp,
            Volume = entity.Volume,
            ExternalMarketId = entity.ExternalMarketId
        };
    }

    // Chamber control market IDs (for overall Senate/House control)
    private static readonly Dictionary<string, string> ChamberMarketIds = new()
    {
        { "Senate", "562794" },  // Which party will control the Senate?
        // Add House market ID here when available
    };

    /// <summary>
    /// Gets the overall chamber control odds from Polymarket.
    /// </summary>
    public async Task<MarketOdds?> GetChamberOddsAsync(string chamber, CancellationToken cancellationToken = default)
    {
        if (!ChamberMarketIds.TryGetValue(chamber, out var marketId))
        {
            _logger.LogDebug("No Polymarket market ID for chamber {Chamber}", chamber);
            return null;
        }

        var raceId = $"CHAMBER-{chamber.ToUpper()}";

        try
        {
            var url = $"{MarketsApiBaseUrl}/{marketId}";
            _logger.LogInformation("Fetching Polymarket chamber odds from {Url}", url);

            var response = await _httpClient.GetAsync(url, cancellationToken);

            if (!response.IsSuccessStatusCode)
            {
                _logger.LogWarning("Polymarket API returned {Status} for chamber market {MarketId}",
                    response.StatusCode, marketId);
                return null;
            }

            var content = await response.Content.ReadAsStringAsync(cancellationToken);
            var market = JsonSerializer.Deserialize<PolymarketMarketResponse>(
                content,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            if (market == null)
            {
                _logger.LogWarning("Failed to parse Polymarket response for chamber market {MarketId}", marketId);
                return null;
            }

            return ParseMarketResponse(market, raceId, marketId);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error fetching chamber market {MarketId}", marketId);
            return null;
        }
    }

    /// <summary>
    /// Returns the daily Dem win-probability series for a race from Polymarket's CLOB price history,
    /// back to <paramref name="startDate"/>. Empty if the race has no configured market. Used by the
    /// retrospective model backfill to reconstruct the market input on each past day.
    /// </summary>
    public async Task<List<(DateTime date, double demProb)>> GetDailyOddsSeriesAsync(
        string raceId, DateTime startDate, CancellationToken cancellationToken = default)
    {
        if (!RaceIdToMarketId.TryGetValue(raceId, out var marketId))
            return new List<(DateTime, double)>();

        return await FetchClobHistoryForRaceAsync(raceId, marketId, startDate, cancellationToken)
               ?? new List<(DateTime, double)>();
    }

    private async Task<List<(DateTime date, double demProb)>?> FetchClobHistoryForRaceAsync(
        string raceId, string marketId, DateTime startDate, CancellationToken cancellationToken)
    {
        try
        {
            // Step 1: Fetch the market from gamma API to get CLOB token IDs and outcomes
            var url = $"{MarketsApiBaseUrl}/{marketId}";
            var response = await _httpClient.GetAsync(url, cancellationToken);
            if (!response.IsSuccessStatusCode) return null;

            var content = await response.Content.ReadAsStringAsync(cancellationToken);
            var market = JsonSerializer.Deserialize<PolymarketMarketResponse>(
                content, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
            if (market == null) return null;

            var clobTokenIds = market.GetClobTokenIds();
            var outcomes = market.GetOutcomes();
            if (clobTokenIds.Count < 2 || outcomes.Count < 2) return null;

            // Step 2: Determine which token index represents Democrat win probability
            int demTokenIndex = GetDemTokenIndex(outcomes, market.Question);
            if (demTokenIndex < 0 || demTokenIndex >= clobTokenIds.Count) return null;

            bool invertPrice = false;
            string tokenId;

            if (demTokenIndex >= 0)
            {
                tokenId = clobTokenIds[demTokenIndex];
            }
            else
            {
                // Fallback: use the first token and invert if it's Republican
                tokenId = clobTokenIds[0];
                invertPrice = true;
            }

            // Step 3: Fetch historical prices from CLOB API
            var historyUrl = $"{ClobApiBaseUrl}/prices-history?market={tokenId}&interval=all&fidelity=1440";
            var historyResponse = await _httpClient.GetAsync(historyUrl, cancellationToken);
            if (!historyResponse.IsSuccessStatusCode)
            {
                _logger.LogWarning("CLOB API returned {Status} for token history", historyResponse.StatusCode);
                return null;
            }

            var historyContent = await historyResponse.Content.ReadAsStringAsync(cancellationToken);
            var historyData = JsonSerializer.Deserialize<ClobPriceHistoryResponse>(
                historyContent, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            if (historyData?.History == null || historyData.History.Count == 0) return null;

            // Step 4: Convert to (date, demProb) pairs, filtering from startDate
            var result = new List<(DateTime, double)>();
            foreach (var point in historyData.History)
            {
                var date = DateTimeOffset.FromUnixTimeSeconds(point.T).UtcDateTime;
                if (date < startDate) continue;

                var demProb = invertPrice ? (1.0 - point.P) : point.P;
                demProb = Math.Max(0.01, Math.Min(0.99, demProb));
                result.Add((date.Date, demProb));
            }

            _logger.LogDebug("Fetched {Count} CLOB history points for {RaceId}", result.Count, raceId);
            return result;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Error fetching CLOB history for {RaceId}", raceId);
            return null;
        }
    }

    private static int GetDemTokenIndex(List<string> outcomes, string? question)
    {
        for (int i = 0; i < outcomes.Count; i++)
        {
            var outcome = outcomes[i].ToLowerInvariant();

            if (outcome.Contains("democrat") || outcome.Contains("dem"))
                return i;

            // For "Yes/No" markets, "Yes" corresponds to the party in the question
            if (outcome == "yes" && question != null)
            {
                if (question.ToLowerInvariant().Contains("democrat"))
                    return i; // "Yes" = Democrat wins
                if (question.ToLowerInvariant().Contains("republican"))
                    return i == 0 ? 1 : 0; // "Yes" = Republican wins, so "No" index = Democrat
            }
            if (outcome == "no" && question != null)
            {
                if (question.ToLowerInvariant().Contains("republican"))
                    return i; // "No" to Republican = Democrat wins
                if (question.ToLowerInvariant().Contains("democrat"))
                    return i == 0 ? 1 : 0; // "No" to Democrat = Republican wins
            }
        }

        // Default: assume second token is Democrat (common in "Will Republicans win?" markets)
        return 1;
    }

    // DTO for Polymarket /markets/{id} API response
    private class PolymarketMarketResponse
    {
        public string? Id { get; set; }
        public string? Question { get; set; }
        public string? ConditionId { get; set; }
        public string? Volume { get; set; }
        public string? Outcomes { get; set; }
        public string? OutcomePrices { get; set; }
        public string? ClobTokenIds { get; set; }
        public string? GroupItemTitle { get; set; }
        public bool? Active { get; set; }
        public bool? Closed { get; set; }

        public List<string> GetOutcomes()
        {
            if (string.IsNullOrEmpty(Outcomes)) return new List<string>();
            try
            {
                return JsonSerializer.Deserialize<List<string>>(Outcomes) ?? new List<string>();
            }
            catch
            {
                return new List<string>();
            }
        }

        public List<string> GetOutcomePrices()
        {
            if (string.IsNullOrEmpty(OutcomePrices)) return new List<string>();
            try
            {
                return JsonSerializer.Deserialize<List<string>>(OutcomePrices) ?? new List<string>();
            }
            catch
            {
                return new List<string>();
            }
        }

        public List<string> GetClobTokenIds()
        {
            if (string.IsNullOrEmpty(ClobTokenIds)) return new List<string>();
            try
            {
                return JsonSerializer.Deserialize<List<string>>(ClobTokenIds) ?? new List<string>();
            }
            catch
            {
                return new List<string>();
            }
        }
    }

    // DTO for CLOB API /prices-history response
    private class ClobPriceHistoryResponse
    {
        public List<ClobPricePoint> History { get; set; } = new();
    }

    private class ClobPricePoint
    {
        public long T { get; set; }
        public double P { get; set; }
    }
}
